/**
 * Generated by tools/images.mjs — do not edit by hand.
 *
 * Dimensions travel with each entry so every <Image> reserves its box before
 * the file arrives, and the blur placeholder is inlined so nothing pops.
 */

export type SiteImage = {
  src: string;
  width: number;
  height: number;
  alt: string;
  blurDataURL: string;
  credit: { author: string; url: string };
};

export const IMAGES = {
  hero: {
    src: "/images/glasshouse-corridor.jpg",
    width: 2800,
    height: 1866,
    alt: "The central corridor of a commercial tomato glasshouse, rows of plants running away on both sides under a diffusing screen, the far door small in the distance.",
    credit: { author: "Rajeeb roy", url: "https://www.pexels.com/photo/modern-greenhouse-with-rows-of-growing-tomatoes-38551884/" },
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAANABQDASIAAhEBAxEB/8QAFwABAQEBAAAAAAAAAAAAAAAABAADBf/EABsQAAICAwEAAAAAAAAAAAAAAAECAAMEESEF/8QAFQEBAQAAAAAAAAAAAAAAAAAAAQD/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDm1ekjsOTa7MWsd3B4+OiHgimqWwaYQI7emu+Shr8ZFsIEpB//2Q==",
  },
  pipeRail: {
    src: "/images/pipe-rail-aisle.jpg",
    width: 2400,
    height: 1800,
    alt: "Looking down the aisle of a high-wire tomato glasshouse: two rows of plants heavy with ripening fruit on either side, and the pair of steel heating pipes that serve as the trolley rail running away to the vanishing point.",
    credit: { author: "Lyn Ong", url: "https://www.pexels.com/photo/fresh-cherry-tomatoes-growing-on-a-greenhouse-5005518/" },
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAAPABQDASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAQFAwb/xAAfEAACAgIBBQAAAAAAAAAAAAABAwACBBFBBRITMWH/xAAWAQEBAQAAAAAAAAAAAAAAAAABAAP/xAAWEQEBAQAAAAAAAAAAAAAAAAAAARH/2gAMAwEAAhEDEQA/AJlK2owW+x3qDi5a6jgTbDw/Ke6/oSi/BUxetaIEzkGOXK7DiEfbhWqwjcJZTj//2Q==",
  },
  diffuseRow: {
    src: "/images/diffuse-row.jpg",
    width: 2400,
    height: 1600,
    alt: "Tomato plants under flat, diffuse glasshouse light, green trusses still setting, the aisle falling out of focus behind them.",
    credit: { author: "Anna Tarazevich", url: "https://www.pexels.com/photo/flower-buds-on-branches-7299952/" },
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAANABQDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAME/8QAHRAAAgICAwEAAAAAAAAAAAAAAQIAAxEhBAVBMf/EABYBAQEBAAAAAAAAAAAAAAAAAAABA//EABURAQEAAAAAAAAAAAAAAAAAAAAR/9oADAMBAAIRAxEAPwClHODqBjUsOwC+THSgVcARZu1RjG5mNh7B1+LqJVqVONeRFWP/2Q==",
  },
  glasshouse: {
    src: "/images/dutch-glasshouse.jpg",
    width: 2400,
    height: 1600,
    alt: "A modern Venlo glasshouse in South Holland seen from outside, its glazing bars running the length of the bay with the crop visible inside.",
    credit: { author: "Igor Passchier", url: "https://www.pexels.com/photo/modern-greenhouse-with-tomato-plants-in-south-holland-36917505/" },
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAANABQDASIAAhEBAxEB/8QAFwABAQEBAAAAAAAAAAAAAAAAAAUDBP/EACAQAAIBAwQDAAAAAAAAAAAAAAABAgMFEQQSEyEjMTP/xAAWAQEBAQAAAAAAAAAAAAAAAAABAAP/xAAWEQEBAQAAAAAAAAAAAAAAAAAAARH/2gAMAwEAAhEDEQA/AO93qGX2ZK8KTb3YJLrR78URywx8ome0qr10Jvc6gJXOl6poEX//2Q==",
  },
  truss: {
    src: "/images/truss-on-the-vine.jpg",
    width: 2400,
    height: 1600,
    alt: "Trusses of tomatoes on the vine at every stage at once — green, breaker, turning and fully red fruit hanging on the same plants.",
    credit: { author: "Cá Bảo", url: "https://www.pexels.com/photo/ripe-and-unripe-cherry-tomatoes-on-the-vine-37443334/" },
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAANABQDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwQA/8QAGxAAAgIDAQAAAAAAAAAAAAAAAQIAEQMSITH/xAAWAQEBAQAAAAAAAAAAAAAAAAACAwT/xAAXEQEBAQEAAAAAAAAAAAAAAAAAEQFB/9oADAMBAAIRAxEAPwAgVyJZ8iIynBpfIGQ1iNck+xVR2ZleTVmipwGhNImdifZowr//2Q==",
  },
  row: {
    src: "/images/high-wire-row.jpg",
    width: 1867,
    height: 2800,
    alt: "A high-wire tomato row from close up, fruit set along the stems at picking height, the aisle running away behind it.",
    credit: { author: "Fer Martinez Gonzalez", url: "https://www.pexels.com/photo/plantation-of-tomatoes-8180574/" },
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAAeABQDASIAAhEBAxEB/8QAGQAAAwEBAQAAAAAAAAAAAAAAAAEFBAMG/8QAIhAAAgICAQMFAAAAAAAAAAAAAQIAAxEhBAUxURITIzJB/8QAFwEAAwEAAAAAAAAAAAAAAAAAAQIDAP/EABcRAQEBAQAAAAAAAAAAAAAAAAARASH/2gAMAwEAAhEDEQA/AJruVyV+pj41jBg/7OzFAgGAT4iSnOwcCRoPScfqiLQgY7xCSqeKGrBJhHozU+qtQ3maKlHrwO0xUFt7mqmw94k6bM4r1KPbEIqrPjGoSjP/2Q==",
  },
  crates: {
    src: "/images/stacked-crates.jpg",
    width: 2400,
    height: 1600,
    alt: "Hundreds of stacked harvest crates seen from above, filling the frame, with a single worker moving between them for scale.",
    credit: { author: "Fatih Kopcal", url: "https://www.pexels.com/photo/worker-in-large-greenhouse-farm-setting-32738498/" },
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAANABQDASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAQFAQP/xAAcEAACAwEAAwAAAAAAAAAAAAABAgADIRESEyL/xAAWAQEBAQAAAAAAAAAAAAAAAAAAAQL/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwCotvkQJ2exSAvdkyqwrsdADqGI2ZVvv5hhFnH0dhA//9k=",
  },
  hand: {
    src: "/images/hand-at-the-vine.jpg",
    width: 1866,
    height: 2800,
    alt: "A picker's hand under a truss of green tomatoes, taking the weight of the cluster without pulling on it.",
    credit: { author: "Anna Tarazevich", url: "https://www.pexels.com/photo/a-hand-touching-the-fruits-on-a-plant-7299950/" },
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAAeABQDASIAAhEBAxEB/8QAGQAAAwEBAQAAAAAAAAAAAAAAAAQFAwEC/8QAHRAAAgIDAQEBAAAAAAAAAAAAAQIAEQMSIQQTBf/EABcBAAMBAAAAAAAAAAAAAAAAAAABAgP/xAAWEQEBAQAAAAAAAAAAAAAAAAAAARH/2gAMAwEAAhEDEQA/APQy5nHVM59HPAKldxjxqdlAMTUBiSVoXMTssJMmVjYMJVUYQo5CPSxs+H6Ek9MU9Dr5xoDbSkjDWqkr9EKmS67DFWst3fooQixZm6DQhKxL/9k=",
  },
} as const satisfies Record<string, SiteImage>;

export type ImageKey = keyof typeof IMAGES;
